services:
  # Backend API - Node.js web service
  - type: web
    name: jnotes-api
    runtime: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install && npm run prisma:generate && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lifetrails-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Frontend - Static site
  - type: web
    name: jnotes-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://jnotes-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    autoDeploy: true

databases:
  # PostgreSQL database (already exists on Render)
  - name: lifetrails-db
    plan: basic-1gb
    region: oregon
    databaseName: jnotes
    user: jnotes
